### ISSUE TITLE
StackedBarChart: java.lang.IndexOutOfBoundsException when there is a tooltip and any value=0

### ISSUE THREAD

**Issue by morthek** [diogobernardino/WilliamChart#110]
When one of the value is equal 0 (i tried 0.1f too), fact that makes this part of the stacked bar not appear, touching the chart brings up and exception. Only happens when a tooltip is added. In case the values have no 0s, the tooltip works normally.

mLabels = new String[]{"10/2015","11/2015", "12/2015", "01/2016"};
mValues = new float[][]{{60f, 30f, 20f,10f}, {30f, 10f, 50f,0}, {40f, 15f, 25f,7f},{5f,43f,56f,15f}};

Stacktrace:
`E/MessageQueue-JNI: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                         at java.util.ArrayList.get(ArrayList.java:308)
                                                                         at com.db.chart.view.ChartView.onTouchEvent(ChartView.java:866)
                                                                         at android.view.View.dispatchTouchEvent(View.java:8476)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                         at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                         at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                         at android.app.Activity.dispatchTouchEvent(Activity.java:2752)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                         at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                         at android.view.View.dispatchPointerEvent(View.java:8671)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4193)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4059)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3740)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3797)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5912)
                                                                         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5851)
                                                                         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5822)
                                                                         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6002)
                                                                         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                         at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                         at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                         at android.os.Looper.loop(Looper.java:122)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                         at java.lang.reflect.Method.invoke(Native Method)`

**Comment by nathan2day** [comment]
I have a similar stacktrace (**ChartView.onTouchEvent - ChartView.java:866**), in my case the 1st region has 5 entries and the 2nd region has 4 entries, both barsets have 6 bars:

mRegions = {ArrayList@830035990960}  size = 2
 0 = {ArrayList@830035990336}  size = 5
 1 = {ArrayList@830035990072}  size = 4

data = {ArrayList@830036041928}  size = 2
 0 = {BarSet@830036986424} 
  mEntries = {ArrayList@830036982080}  size = 6
  mAlpha = 1.0
  mIsVisible = true
 1 = {BarSet@830036995544} 
  mEntries = {ArrayList@830036988376}  size = 6
  mAlpha = 1.0
  mIsVisible = true

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              java.lang.IndexOutOfBoundsException: Invalid index 4, size is 4
                                                                                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                  at java.util.ArrayList.get(ArrayList.java:308)
                                                                                  at **com.db.chart.view.ChartView.onTouchEvent(ChartView.java:866)**
                                                                                  at android.view.View.dispatchTouchEvent(View.java:7767)
                                                                                  
The exception can be prevented by setting the number of entries inside the first of the two for loops:

extract of ChartView.onTouchEvent source:
				int nSets = mRegions.size();
				**int nEntries = mRegions.get(0).size();  // move to within the 1st for loop**
				for(int i = 0; i < nSets ; i++){
				**int nEntries = mRegions.get(i).size();  // move to here**
					for(int j = 0; j < nEntries; j++){

						if(mRegions.get(i).get(j)
								.contains((int) event.getX(),
										(int) event.getY())){
							mSetClicked = i;
							mIndexClicked = j;
						}
					}
				}

However, should the number of regions by the same? The above change may prevent the exception when the actual fix is to work out why the number of entries do not match in each region?

**Comment by joeykrim** [comment]
I'm encountering the same issue: whenever the chart (I'm testing with StackBarChart) is touched or the device screen is rotated, the application crashes.

For a little more clarity, two conditions must exist to cause the crash:
1) A chart value is <1 and >= 0, which is supported with float values
2) The setOnEntryClickListener is attached to the chart

The crash stack trace provided above is the same as what I've experienced: IndexOutOfBoundsException at com.db.chart.view.ChartView.onTouchEvent([ChartView.java:866](https://github.com/diogobernardino/WilliamChart/blob/master/library/src/com/db/chart/view/ChartView.java#L866))

Using stackBarChart, each column requires a value. If a column has a legitimate value of 0, the ClickListener can't be attached.

**Comment by nathan2day** [comment]
Thanks to @joeykrim for the positive comments, it's spurred me on to look into the regions.

It would seem that the following **StackBarChartView.defineRegions** code to skip creating regions for invisible, small or zero height bars on the stacked charts differs from the non-stacked charts, that difference being that the non stacked charts will create regions with zero height (top = bottom when creating the regions).

Perhaps, as we have found there to be a need to have a region for all bars (so that the region indexes match with the entry indexes), the stacked charts could do the same to resolve this?


                // If:
                // Bar not visible OR
                // Bar value equal to 0 OR
                // Size of bar < 2 (Due to the loss of precision)
                // Then no need to have region
                if(!barSet.isVisible() || bar.getValue() == 0 || barSize < 2) {

**START INSERTED CODE (note braces around continue too)**

					// create zero height region to match non-stacked bar chart behaviour
					result.get(j).add(new Region(
                            (int) (bar.getX() - barWidth / 2),
							(int) this.getZeroPosition(),
                            (int) (bar.getX() - barWidth / 2),
                            (int) this.getZeroPosition()));

**END INSERTED CODE**

                    continue;
                }

                if(bar.getValue() > 0) {

                    y1 = zeroPosition - (barSize + verticalOffset);
                    result.get(j).add(new Region(
                            (int) (bar.getX() - barWidth / 2),
                            (int) y1,
                            (int) (bar.getX() + barWidth / 2),
                            (int) currBottomY));

                    currBottomY = y1;
                    verticalOffset += barSize + 2;
                }else{

                    y1 = zeroPosition + (barSize - negVerticalOffset);
                    result.get(j).add(new Region(
                            (int) (bar.getX() - barWidth / 2),
                            (int) negCurrBottomY,
                            (int) (bar.getX() + barWidth / 2),
                            (int) y1));

                    negCurrBottomY = y1;
                    negVerticalOffset -= barSize;
                }

**Comment by diogobernardino** [comment]
Fixed in #130.
