### ISSUE TITLE
ArrayIndexOutOfBoundsException in LineChartView

### ISSUE THREAD

**Issue by stubags** [diogobernardino/WilliamChart#161]
Hi,

I'm trying to use the LineChartView within my android project and getting the below exception.  I tried pre-loading with data to avoid ever having the chart empty to begin with before data is loaded,  but this has not helped.  Please advise.

Thanks

10-28 14:17:58.377  20326-20326/com.example.sam_chordas.stockhawk E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.sam_chordas.stockhawk, PID: 20326
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.db.chart.renderer.XRenderer.measureInnerChartLeft(XRenderer.java:146)
            at com.db.chart.renderer.XRenderer.measure(XRenderer.java:52)
            at com.db.chart.view.ChartView$1.onPreDraw(ChartView.java:158)
            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2560)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7450)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
            at android.view.Choreographer.doCallbacks(Choreographer.java:695)
            at android.view.Choreographer.doFrame(Choreographer.java:631)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:7229)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by diogobernardino** [comment]
Not sure what you're doing wrong. The only thing I can say, not just based on the exception but also at the line of code where it breaks, is that your set of labels is empty, that should never happen.
