### ISSUE TITLE
Using Line Chart In RecyclerView Error  Paint.getNativeInstance()' on a null object reference

### ISSUE THREAD

**Issue by sahilwebmazix** [diogobernardino/WilliamChart#162]
i am using LineChart with Grid Here is My code i am  getting an  error in set Grid Method when Scrolling its Crashes with Error NullPointerException : - 
`paint = new Paint();
            paint.setColor(curr_activity.getResources().getColor(R.color.whiteLight));
            linechart.setGrid(ChartView.GridType.FULL, 10, mLabels.length, paint);` 

 java.lang.NullPointerException: Attempt to invoke virtual method 'long   android.graphics.Paint.getNativeInstance()' on a null object reference.
     ` at android.graphics.Canvas.drawLine(Canvas.java:1073)
                                                                           at com.db.chart.view.ChartView.drawVerticalGrid(ChartView.java:800)
                                                                           at com.db.chart.view.ChartView.onDraw(ChartView.java:730)
                                                                           at android.view.View.draw(View.java:16178)
                                                                           at android.view.View.buildDrawingCacheImpl(View.java:15474)
                                                                           at android.view.View.buildDrawingCache(View.java:15335)
                                                                           at android.view.View.draw(View.java:15941)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                           at android.view.View.draw(View.java:15948)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                           at android.view.View.draw(View.java:16181)
                                                                           at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:1628)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                           at android.view.View.draw(View.java:15948)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                           at android.view.View.draw(View.java:15948)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                           at android.view.View.draw(View.java:16181)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                           at android.view.View.draw(View.java:15948)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                           at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3838)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                           at android.view.View.draw(View.java:16181)
                                                                           at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3308)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573
11-02 18:37:38.669 21654-21654/apps.webmaazix.envolo I/Process: Sen`

**Comment by diogobernardino** [comment]
Duplicate #98 ?
