### ISSUE TITLE
java.lang.IllegalArgumentException: text cannot be null

### ISSUE THREAD

**Issue by hrsalehi** [diogobernardino/WilliamChart#166]
Hi.

some of my app users got this error and I can't reproduce it to solve the problem. can you give me any hint?

```
java.lang.IllegalArgumentException: text cannot be null
	at android.graphics.Paint.measureText(Paint.java:1957)
	at com.db.chart.view.XController.measureInnerChartRight(SourceFile:109)
	at com.db.chart.view.XController.measure(SourceFile:46)
	at com.db.chart.view.ChartView$1.onPreDraw(SourceFile:179)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2510)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)```

**Comment by diogobernardino** [comment]
Maybe you're are setting some labels as _null_?

**Comment by hrsalehi** [comment]
all labels generated from float and integer values. I think the problem is from where I want to set YAxis thresholds. 
For now I just updated library to 2.3.0 and surrounded the block with try/catch

**Comment by diogobernardino** [comment]
I cannot see how a threshold can influence this part of the code, not sure if I'm missing something. From what you posted I continue to believe that somehow you end up with a null X label, which breaks your code once trying to do the ```measureText(xLabel)```.

**Comment by diogobernardino** [comment]
Could you get anything else...?

**Comment by hrsalehi** [comment]
I just updated the library to the latest version and then added some exception handling blocks around suspicious areas.
So far I didn't see any exceptions or errors in my logging mechanism But I am not sure that the same exception doesn't raise any more.

**Comment by diogobernardino** [comment]
Ok, it would be also good to have a check on whether there is any null label or not when this exception is raised. Quick question: what you have is an horizontal chart, correct? For the time being I will keep the issue opened hoping to have some more information.

**Comment by hrsalehi** [comment]
I have a weight chart. So I have a maximum and minimum weights in vertical order (y) and the days in horizontal (x) order. Some situations users add assume two weights the same some the maximum and minimum are the same and the result is a exception that max and min should be different.

In the horizontal order I have dates placed as a ```Calendar``` and sometimes this instance could be null. I managed to prevent sending null values to the horizontal labels but I think the older version of chart didn't handle null values for labels.

**Comment by diogobernardino** [comment]
Yes, for obvious reasons there's no way a chart can have the same minimum and maximum.
Ok, in that case the problem is clear, this dates in x labels should never be null. In case you want to skip labels use a an empty string.

**Comment by hrsalehi** [comment]
Yeah I think that was the problem. But in my example I couldn't find why some dates become null so I handled this ```NullPointerException``` so chart doesn't face same problem. But I think something changed since my update from older versions.A problem that doesn't exist in the latest version.

**Comment by diogobernardino** [comment]
Actually now that you mention that I see that the log is from an older version as the exception is raised from XController, a class that was refactored and renamed to XRenderer in the latest version.

I consider the issue closed.
