### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3

### ISSUE THREAD

**Issue by hi-manshu** [diogobernardino/WilliamChart#215]
at java.util.ArrayList.get(ArrayList.java:411)
                                                                                        at com.db.chart.view.LineChartView.defineRegions(LineChartView.java:159)
                                                                                        at com.db.chart.view.ChartView$1.onPreDraw(ChartView.java:224)
                                                                                        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2238)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1280)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6451)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:943)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:755)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:690)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:929)
                                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6334)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)

**Comment by hi-manshu** [comment]
Getting this issue everytime i am adding it into a fragment

**Comment by diogobernardino** [comment]
Can you show some code, in particular when you prepare and add data to chart?

**Comment by JoachimR** [comment]
```
val dataset = LineSet()
dataset.addPoint(Point("a", 1f))
dataset.addPoint(Point("b", 2f))

linechart.addData(dataset)
linechart.show()
```
inside a `android.support.v4.app.Fragment` after `onActivityCreated()`

**Comment by diogobernardino** [comment]
What's your exception @JoachimR ?
Are you adding data more than once without resetting (`ChartView.reset()`) before?

**Comment by JoachimR** [comment]
I had the same exception `size:1 index:1`.

I did not use any `reset()` beforehand. I create and start the Fragment and run the code from above

**Comment by diogobernardino** [comment]
Not observed in `v3.x`.
