### ISSUE TITLE
Issue with less then 10 points

### ISSUE THREAD

**Issue by chnouman** [diogobernardino/WilliamChart#226]
i have to show only five points on the line chart2 but it is showing nothing.

**Comment by chnouman** [comment]
```
 Process: com.binrafiq.starling, PID: 11089
                                                                       java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
                                                                           at java.util.ArrayList.get(ArrayList.java:411)
                                                                           at com.db.chart.view.LineChartView.defineRegions(LineChartView.java:159)
                                                                           at com.db.chart.view.ChartView$1.onPreDraw(ChartView.java:224)
                                                                           at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2517)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1526)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7102)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by diogobernardino** [comment]
Not reproducible in `v3.x`. Little info provided.
