### ISSUE TITLE
My app crashes on ChartView.onTouchEvent 

### ISSUE THREAD

**Issue by bojan2110** [diogobernardino/WilliamChart#228]
Hi! 

First of all, thank you for the library I find it very useful for my project.
Now about my problem: I have implemented StackBarChart with two values on each bar. So I am setting this type of dataset: mValuesOne ={{6000f, 1000f, 7000f, 3500f},{2000f, 2000f, 2000f, 200f}}.

I want to show the user some information, as he clicks a particular bar. However, when the values of one BarSet are too small , lets say   mValuesOne ={{6000f, 1000f, 7000f, 3500f},{10f, 5f, 2f, 2f}}, visually in my app the second BarSet is insignificant ( so visually its like not displayed, and this is what I want), but this seems to confuse the ChartView.onTouchEvent, with the following error:

> java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                      at java.util.ArrayList.get(ArrayList.java:308)
                      at com.db.chart.view.ChartView.onTouchEvent(ChartView.java:866)
                      at android.view.View.dispatchTouchEvent(View.java:8476)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)

> 

When the mValuesOne are defined in a way where the ratio is good, like mValuesOne ={{6000f, 1000f, 7000f, 3500f},{100f, 500f, 200f, 200f}}, touch events have no problem whatsoever.

Any ideas how to solve this? 
As in my scenario, sometimes it can happen that the second BarSet have even 0s.

Thanks
Bojan

**Comment by diogobernardino** [comment]
Version 2.x has been discontinued, I just published v3.0 completely rewritten from scratch but still with limited features.
