### ISSUE TITLE
App is crashing when all vaules are 0 

### ISSUE THREAD

**Issue by yeshwanthmunisifreddy** [diogobernardino/WilliamChart#246]
java.lang.RuntimeException: Unable to resume activity {in.hexalab.sample/in.hexalab.sample.activity.HomeActivity}: java.lang.IllegalArgumentException: Minimum border value must be greater than maximum values
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3672)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3712)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2949)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.IllegalArgumentException: Minimum border value must be greater than maximum values
        at com.db.chart.renderer.AxisRenderer.setBorderValues(AxisRenderer.java:567)
        at com.db.chart.view.ChartView.setAxisBorderValues(ChartView.java:1116)
        at com.db.chart.view.BaseStackBarChartView.calculateMaxStackBarValue(BaseStackBarChartView.java:165)
        at com.db.chart.view.BaseStackBarChartView.show(BaseStackBarChartView.java:179)
        at in.hexalab.sample.fragment.TodayFragment.setStackedChartData(TodayFragment.java:263)
        at in.hexalab.sample.fragment.TodayFragment.setData(TodayFragment.java:114)
        at in.hexalab.sample.fragment.TodayFragment.onCreateView(TodayFragment.java:68)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7164)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3647)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3712) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2949) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6626) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by diogobernardino** [comment]
Can't reproduce in v3.
