### ISSUE TITLE
crash on tooltip onDataPointTouch

### ISSUE THREAD

**Issue by taouichaimaa** [diogobernardino/williamchart#308]
I want to show the value of the touched datapoint, so I used this:
` binding.includedCharts.sparkeyView.onDataPointTouchListener = { index, _, _ -> binding.includedCharts.showdata.text =
                        myset.toList()[index] .second .toString()
                }`
However I get this error : 
`MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: kotlin.UninitializedPropertyAccessException: lateinit property tooltipView has not been initialized
        at com.db.williamchart.slidertooltip.SliderTooltip.onDataPointTouch(SliderTooltip.kt:27)
        at com.db.williamchart.view.AxisChartView.onTouchEvent(AxisChartView.kt:147)`

**Comment by ishdemon** [comment]
same here..too bad this seemed like a good charting library

**Comment by tejas-bhong** [comment]
Facing same issue!
