### ISSUE TITLE
LineChart IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by ArtemGulia** [diogobernardino/WilliamChart#40]
I have IndexOutOfBoundsException when I'm trying add several Points(" ", 0) to lineSet and trying to show LineChartView

java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
            at java.util.ArrayList.get(ArrayList.java:304)
            at com.db.chart.view.YController.parseYPos(YController.java:282)
            at com.db.chart.view.ChartView$1.onPreDraw(ChartView.java:135)
            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:671)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1818)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
            at android.view.Choreographer.doCallbacks(Choreographer.java:555)
            at android.view.Choreographer.doFrame(Choreographer.java:525)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by diogobernardino** [comment]
Have you tried to define the min and/or max values of the axis?

**Comment by ArtemGulia** [comment]
No. How can I do that?  With this method?
setAxisBorderValues(int minValue, int maxValue, int step)

**Comment by diogobernardino** [comment]
Yes, that method.

**Comment by ArtemGulia** [comment]
Ok, I'll try and write here results.
Thanks.

**Comment by ArtemGulia** [comment]
Awesome!
Thanks a lot, it fixes my problem!

**Comment by tsherdiwala** [comment]
The issue resurfaces:

```
 java.lang.IndexOutOfBoundsException: Index: 31, Size: 31
                                                                       at java.util.ArrayList.get(ArrayList.java:411)
                                                                       at com.db.chart.view.LineChartView.defineRegions(LineChartView.java:177)
                                                                       at com.db.chart.view.ChartView$1.onPreDraw(ChartView.java:195)
                                                                       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2513)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7098)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
```

Happens when the data in the graph are modified twice.

**Comment by eladnava** [comment]
@tsherdiwala Just reproduced. Attempting to find a workaround.

**Comment by diogobernardino** [comment]
Details? The exception shared by @tsherdiwala seems different than the initial issue.

**Comment by eladnava** [comment]
@diogobernardino Sure, first, create a `LineChartView`.  Then, show it with some data. Next, modify the data (add more line points) and call `.show()` on the same chart. This causes the crash.

**Comment by eladnava** [comment]
@diogobernardino FYI the crash is in `LineChartView.java` in the following line:

```java
regions.get(i)
                        .get(j)
                        .set((int) (x - mClickableRadius), (int) (y - mClickableRadius),
                                (int) (x + mClickableRadius), (int) (y + mClickableRadius));
```

**Comment by eladnava** [comment]
A workaround I have implemented for now calls `setClickableRegions` via reflection to reset the `regions` array list:

```java
 // Workaround for chart redraw crash
        try {
            // Get "setClickableRegions()" private method
            Method method = ChartView.class.getDeclaredMethod("setClickableRegions", new ArrayList<ArrayList<Region>>().getClass());
            method.setAccessible(true);

            // Clear the clickable regions
            method.invoke(mChart, new ArrayList<ArrayList<Region>>());
        }
        catch (Exception exc) {
            // Log error
            Log.e(Logging.TAG, "Resetting chart regions failed");
        }
```

**Comment by diogobernardino** [comment]
If you want to _change the number of points_ you should use `reset()` and then rebuild your chart with the new data. If your data changes but still _keeps the same number of points_ you can use `updateValues `instead.

**Comment by eladnava** [comment]
Ah @diogobernardino, thanks for the clarification!

I have documented this in the Wiki:
https://github.com/diogobernardino/WilliamChart/wiki/(2)-Chart
