### ISSUE TITLE
IndexOutOfBoundsException when displaying a bar graph with zero values.

### ISSUE THREAD

**Issue by bilthon** [diogobernardino/WilliamChart#58]
I'm using a bar graph and this happens whenever I set all the values for the bars to zero. I'm not trying to update the graph while it still animating or anything like that. It is just that my user generated data will be retrieved as all zeroes.

Here's the stack trace I get:
```java
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.db.chart.view.YController.parsePos(YController.java:97)
        at com.db.chart.view.ChartView$1.onPreDraw(ChartView.java:143)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1956)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:550)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```
And this is a simplified version of my code:

```java
BarChartView chart = (BarChartView) this.getView().findViewById(R.id.barchart);
BarSet barSet = new BarSet();
Bar bar;
float[] barValues = {0.0f, 0.0f};
int[] barColors = { R.color.bar1, R.color.bar2};
String[] labels = {"A","B"};

// Creating bars
for(int i = 0; i < barValues.length; i++){
    bar = new Bar(labels[i], barValues[i]);
    bar.setColor(this.getResources().getColor(barColors[i]));
    barSet.addBar(bar);
}
chart.addData(barSet);
chart.setYAxis(false)
        .setYLabels(AxisController.LabelPosition.NONE)
        .show(new Animation()
                .setEasing(new ElasticEaseOut()));
```
As long as I change one of the values to something different than zero the graph displays just fine.

**Comment by diogobernardino** [comment]
Fix pushed to dev branch.
In case you would like to continue with the version you have at the moment, until I move the fix into master, you can simply set a minimum and a maximum axis value with ```setAxisBorderValues```. That will solve your problem for now.
