### ISSUE TITLE
ArrayIndexOutOfBoundsException possibly caused by empty data set

### ISSUE THREAD

**Issue by XxPixX** [diogobernardino/WilliamChart#72]
Hi, I'm getting the below exception. I believe it's because I'm supplying it an empty data set? Either way, I think it should just display an empty graph if the data set is empty...

version: 2.0.1

java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
            at java.util.ArrayList.get(ArrayList.java:310)
            at com.db.chart.model.ChartSet.getEntry(ChartSet.java:108)
            at com.db.chart.view.LineChartView.drawBackground(LineChartView.java:321)
            at com.db.chart.view.LineChartView.drawLine(LineChartView.java:211)
            at com.db.chart.view.LineChartView.onDrawChart(LineChartView.java:113)
            at com.db.chart.view.ChartView.onDraw(ChartView.java:661)
            at android.view.View.draw(View.java:15231)
            at android.view.View.buildDrawingCacheImpl(View.java:14477)
            at android.view.View.buildDrawingCache(View.java:14339)
            at android.view.View.updateDisplayListIfDirty(View.java:14148)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.support.v4.view.ViewPager.draw(ViewPager.java:2259)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1680)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1074)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayLi

**Comment by XxPixX** [comment]
Hi, a little update: it seems to work after removing         dataSet.setFill(getResources().getColor(R.color.chart_fill_color));

**Comment by diogobernardino** [comment]
Couldn't understand the relation between the exception and setFill method.
In any case, regarding the empty set, I do not cover those cases, I believe each developer should build his own no-data layout that fits better their app.
