### ISSUE TITLE
Divide by Zero in com.db.chart.view.ChartView.setAxisBorderValues(ChartView.java:1118)

### ISSUE THREAD

**Issue by cederom** [diogobernardino/WilliamChart#78]
setAxisBorderValues() can lead to Divide by Zero.

```
09-12 02:49:49.217    8471-8471/com.cederom.iqbabygrowcharts E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.cederom.iqbabygrowcharts, PID: 8471
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cederom.iqbabygrowcharts/com.cederom.iqbabygrowcharts.IQBabyGrowChartsActivity}: java.lang.ArithmeticException: divide by zero
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ArithmeticException: divide by zero
            at com.db.chart.view.ChartView.setAxisBorderValues(ChartView.java:1118)
            at com.cederom.iqbabygrowcharts.IQBabyGrowChartsActivity$IQLineChart.chartDraw(IQBabyGrowChartsActivity.java:95)
            at com.cederom.iqbabygrowcharts.IQBabyGrowChartsActivity.onCreate(IQBabyGrowChartsActivity.java:294)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by diogobernardino** [comment]
Aren't your ``setAxisBorderValues`` args wrong? Can you tell what are you trying to set there?

**Comment by cederom** [comment]
On Sun, Sep 13, 2015 at 6:29 PM, Diogo Bernardino wrote:
> Aren't your setAxisBorderValues args wrong? Can you tell what are you trying to set there?

Yes, it looks like its zero, but library could verify that :-) It
would be even better if we set -1 as step to calculate Greates Common
Denominator. Value of "5" does not always work, so I did max%min but
this sometimes lead to division by zero for particular set of input
data :-)

I will try to fix that after I fix the drawing routine after I finish
my application :-)

-- 
CeDeROM, SQ7MHZ, http://www.tomek.cedro.info

**Comment by diogobernardino** [comment]
That idea sounds like something worth to think about, I will keep the issue open and think about it as a possible future implementation.

**Comment by cederom** [comment]
Thank you :-) If I manage that, will code :-)

--
CeDeROM, SQ7MHZ, http://www.tomek.cedro.info

**Comment by diogobernardino** [comment]
I've added a ``setAxisBorderValues`` method with no need of ``step`` arg, and in that case, if ``min`` value is positive, ``step`` will be set to the GCD. 
The change has been included only in dev branch for the time being.

**Comment by cederom** [comment]
Perfect, tank you!! :-) :-)

-- 
CeDeROM, SQ7MHZ, http://www.tomek.cedro.info
