### ISSUE TITLE
NPE upon drawline in RecyclerView

### ISSUE THREAD

**Issue by rubinovk** [diogobernardino/WilliamChart#98]
hey Diogo! Thank you very much for the great library. 
I've attempted to display BarChart charts within `RecyclerView` and I consistently get NPE at:
`onDraw`->`drawHorizontalGrid`->`canvas.drawLine()` whenever `RecyclerView` shows me an item that was hidden, recycled and then showed again.
I tried to debug the issue, but the only result I've got so far is that I can avoid the exception if I do not create nor set the grid paint object for a chart.
I have some hypotheses, but not sure 100%. I suspect that it has to do with `style.clean()` that is called in `onDetachedFromWindow()` in `ChartView` and resets the paint object. 
Thanks

**Comment by diogobernardino** [comment]
Thanks for reporting. I've never done the test with ```RecyclerView```. It could be indeed something in ```style.init()``` under ```onAttachedToWindow()``` and/or in ```style.clean()``` under ```onDetachedFromWindow()```.
Did you manage to overcome the issue? Give it a try to comment that code and see if it still occurs.

**Comment by narger17** [comment]
any news ?

**Comment by XxPixX** [comment]
@narger17 
As a temporary workaround you can override onAttachedToWindow in your view containing the Chart and set the grid Paint then like so:

@Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        chart.setGrid(ChartView.GridType.FULL, 5, 5, chartGridPaint);
    }

**Comment by narger17** [comment]
right! Thank You Very much :-D

**Comment by joeykrim** [comment]
I'm also seeing some unexpected behavior inside the RecyclerView.

The temporary workaround I used inside the RecyclerView.Adapter, which includes part of the temporary workaround from @XxPixX, is:
```
    @Override
    public void onBindViewHolder(ViewHolder ViewHolder, int position) {
        if (horizontalStackBarChartView.getData().isEmpty()) {
            addDataAndShowChart(horizontalStackBarChartView);
        } else {
            horizontalStackBarChartView.setGrid(ChartView.GridType.FULL, 5, 5, chartGridPaint);
            horizontalStackBarChartView.show();
        }
}
```
To help locate this issue through the searching for the stack trace, I've pasted mine below:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long android.graphics.Paint.getNativeInstance()' on a null object reference
at android.graphics.Canvas.drawLine(Canvas.java:1073)
at com.db.chart.view.ChartView.drawVerticalGrid(ChartView.java:800)
at com.db.chart.view.ChartView.onDraw(ChartView.java:730)
at android.view.View.draw(View.java:16184)
at android.view.View.buildDrawingCacheImpl(View.java:15480)
at android.view.View.buildDrawingCache(View.java:15341)
at android.view.View.draw(View.java:15947)
at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
at android.view.View.updateDisplayListIfDirty(View.java:15175)
at android.view.View.draw(View.java:15954)
at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
at android.view.View.draw(View.java:16187)
at android.view.View.updateDisplayListIfDirty(View.java:15180)
at android.view.View.draw(View.java:15954)
at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3588)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
at android.view.View.draw(View.java:16187)
at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3097)
at android.view.View.updateDisplayListIfDirty(View.java:15180)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
at android.view.View.updateDisplayListIfDirty(View.java:15140)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
```

**Comment by blackberry2016** [comment]
the same issue version 2.5.0

**Comment by diogobernardino** [comment]
I have a sample with more than 20 charts in a RecyclerView and it doesn't to happen.
